spec:
  template:
    spec:
      containers:
        - env:
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mariadb
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mariadb
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: mariadb
            - name: SPRING_PROFILES_ACTIVE
              value: rahti